/tmp/slurmd/job25553/slurm_script: line 13: nvidea-smi: command not found
2025-08-12 22:45:37,102 - INFO - ======================================================================
2025-08-12 22:45:37,102 - INFO -                       Ataque adversarial a LLMs                       
2025-08-12 22:45:37,102 - INFO - ======================================================================
2025-08-12 22:45:37,102 - INFO - ======================================================================
2025-08-12 22:45:37,102 - INFO -                               RESULTADOS                              
2025-08-12 22:45:37,102 - INFO - ======================================================================
2025-08-12 22:45:37,102 - INFO - Importando bibliotecas. . .
2025-08-12 22:45:52,633 - INFO - Bibliotecas importadas
2025-08-12 22:46:17,655 - INFO - Usando cuda
2025-08-12 22:46:17,656 - INFO - Importando dados. . .
2025-08-12 22:46:17,689 - INFO - Dados importados
2025-08-12 22:46:17,689 - INFO - ======================================================================
2025-08-12 22:46:17,689 - INFO -                      Modelo: lmsys/vicuna-7b-v1.5                     
2025-08-12 22:46:17,689 - INFO - ======================================================================
2025-08-12 22:46:17,689 - INFO - ======================================================================
2025-08-12 22:46:17,690 - INFO -                      Modelo: lmsys/vicuna-7b-v1.5                     
2025-08-12 22:46:17,690 - INFO - ======================================================================
2025-08-12 22:46:17,690 - INFO - Importando modelo. . .
/home/CIN/mefc/deteccao/llm-attacks/detec/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/CIN/mefc/deteccao/llm-attacks/detec/lib/python3.10/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards:  50%|█████     | 1/2 [05:06<05:06, 306.13s/it]Downloading shards: 100%|██████████| 2/2 [06:54<00:00, 189.76s/it]Downloading shards: 100%|██████████| 2/2 [06:54<00:00, 207.22s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [01:29<01:29, 89.36s/it]Loading checkpoint shards: 100%|██████████| 2/2 [02:01<00:00, 55.65s/it]Loading checkpoint shards: 100%|██████████| 2/2 [02:01<00:00, 60.71s/it]
2025-08-12 23:20:22,033 - INFO - Modelo importado
2025-08-12 23:20:22,034 - INFO - Importando tokenizer. . .
2025-08-12 23:20:27,733 - ERROR - Erro ao importar bibliotecas: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
